### ISSUE TITLE
Testes de layout do PDF da carta do serviço

### ISSUE THREAD

**Issue by glauberramos** [servicosgovbr/carta-para-pdf#4]

**Comment by sahrosa** [comment]
Oi pessoal! Tá ficando muito legal! Parabéns :D 

Percebi algumas coisinhas que podem ser melhoradas:
- [x] Alguns títulos estão em title case (Quem pode utilizar este serviço) e outros all caps (O QUE É). Sugiro o padrão de title case.
- [x] A sigla do órgão está solta ao lado do nome do órgão. Ideal seria deixa-la entre parenteses.
- [x] Markdown não está funcionando nos solicitantes. Está mostrando o asterisco ao invés de bullets.
- [x] Seria interessante incluir em algum lugar o site do Portal de Serviços, explicando que aquelas informações são coletadas de lá e podem estar desatualizadas, ou então pelo menos dizer qual a data daquela versão da carta.
- [x] Os tipos de canais estão com nomes meio "diretos" como  "web-agendar". Seria interessante mostrar de uma forma mais amigável.
- [x] Talvez valha a pena mostrar o número da página pras pessoas conseguirem ordenar corretamente quando imprimirem
