### ISSUE TITLE
Estudar padrões de design do governo

### ISSUE THREAD

**Issue by glauberramos** [servicosgovbr/carta-para-pdf#5]

**Comment by oliviagj** [comment]
Tu já tá fazendo isso, @raonylima? Passa para doing...

**Comment by raonylima** [comment]
O guia de estilo/identidade do que é feito atualmente do governo:

https://drive.google.com/a/thoughtworks.com/file/d/0B8H3IJw9JWY3SWFrRjNhTmtjLXM/view
